---
dataset_type: 'image'
location_data:
    # input_path: '/home/louisccc/NAS/louisccc/av/roadscene2vec_pkls/5_frame_honda_lane_change.pkl' #5_frame_shortened_1_seq_raw_dataset.pkl'
    input_path: 'D:\research\av_data\20_frame_all_lane_change.pkl'
    data_save_path: 'D:\research\av_data\20_frame_all_lane_change_sg.pkl' #where to save scenegraph dataset
    #TODO: revise this configuration file

relation_extraction_settings:
  framenum: 1000
  ACTOR_NAMES: ['car','moto','bicycle','ped','lane','light','sign', 'road']
  extract_directional_relations: True
  extract_distance_relations: True
  extract_all_car_car_relations: True
  CAR_PROXIMITY_THRESH_NEAR_COLL: 3
  CAR_PROXIMITY_THRESH_SUPER_NEAR: 7 # max number of feet between a car and another entity to build proximity relation
  CAR_PROXIMITY_THRESH_VERY_NEAR: 10
  CAR_PROXIMITY_THRESH_NEAR: 16
  CAR_PROXIMITY_THRESH_VISIBLE: 25
  MOTO_PROXIMITY_THRESH: 50
  LANE_THRESHOLD: 6 #feet. if object's center is more than this distance away from ego's center, build left or right lane relation
  CENTER_LANE_THRESHOLD: 9
  BICYCLE_PROXIMITY_THRESH: 50
  PED_PROXIMITY_THRESH: 50
  MOTO_NAMES: ["Harley-Davidson", "Kawasaki", "Yamaha"]
  BICYCLE_NAMES: ["Gazelle", "Diamondback", "Bh"]
  CAR_NAMES: ["Ford", "Bmw", "Toyota", "Nissan", "Mini", "Tesla", "Seat", "Lincoln", "Audi", "Carlamotors", "Citroen", "Mercedes-Benz", "Chevrolet", "Volkswagen", "Jeep", "Nissan", "Dodge", "Mustang"]
  
image_setttings: #currently tuned for Honda
    BEV_PATH: 'D:\research\roadscene2vec\roadscene2vec\scene_graph\extraction\bev\bev.json'

