---
use_case_5_data:
    visualize: True
    visualize_save_path: 'viz'
    iterations: 1
    inspect_csv_store_path: 'seq_attns.csv'
    RELATION_NAMES: ['isIn', 'inDFrontOf', 'inSFrontOf', 'atDRearOf', 'atSRearOf', 'toLeftOf', 'toRightOf', 'near_coll', 'super_near' , 'very_near', 'near' ,'visible'] #Relations extracted during creation of example scenegraph dataset

location_data:
    input_path: 'use_case_data/1043_carla_scenegraphs.pkl' #'/use_case_5_input_sg.pkl'#path to pkl containing scenegraph dataset training/testing data
    transfer_path: null #path to transfer dataset for transfer learning
    
model_configuration:
  num_relations: 12 #num of types of relations extracted, needed only for graph based models 
  model: 'mrgcn' #options: mrgcn, mrgin
  num_layers: 3 #defines number of RGCN conv layers.
  load_model: True #load pretrained model
  num_of_classes: 9 #8 #num of actors
  conv_type: 'FastRGCNConv'
  hidden_dim: 64
  layer_spec: null
  pooling_type: 'sagpool'
  pooling_ratio: 1.0
  readout_type: 'add'
  temporal_type: 'lstm_attn' #Options: 'lstm_attn' for task 'sequence classification', 'lstm_seq' for task 'collision prediction'
  lstm_input_dim: 50 
  lstm_output_dim: 20
  nclass: 2 #dimension of final output
  dropout: 0.1 #dropout probability
  device: 'cuda' #device to place training/testing data batches
  activation: 'relu'
  model_load_path: 'use_case_data/5_fold_271_carla_sequence_classification_example_model.pt'  #path to load pretrained model
  model_save_path: '' #path to save trained model
   
training_configuration:
  dataset_type: "scenegraph" #Options: real, scenegraph. scenegraph only option for graph based models
  scenegraph_dataset_type: "carla" #type of data extracted to create input scenegraph data. Options: carla, real
  task_type: 'sequence_classification' #Options: sequence_classification, graph_classification, collision_prediction
  n_fold: 2 #number of folds for n-fold cross validation
  learning_rate: 0.0001 #0.00005
  epochs: 200
  split_ratio: 0.3 #train-test split ratio
  downsample: False
  seed: 0 #seed used for train-test split
  batch_size: 32 #batch size of training, testing data
  test_step: 10 #perform test validation every n epochs
  weight_decay: 0.0005
  
wandb_configuration:
  entity: null
  project: null
