---
location_data:
    input_path: '/home/louisccc/NAS/louisccc/av/sg2vec_pkls/571_honda_image_dataset_5_frame_128x72.pkl' #path to pkl containing real image dataset training/testing data
    transfer_path: null #path to transfer dataset for transfer learning
    
model_configuration:
  model: 'cnn_lstm' #options: cnn, cnn_lstm, resnet50, resnet50_lstm, lstm, gru
  load_model: False #load pretrained model
  model_load_path: './model/model_best_val_loss_.vec.pt' #path to load pretrained model
  model_save_path: './model/model_best_val_loss_.vec.pt' #path to save trained model
  dropout: 0.1 #dropout probability
  nclass: 2 #dimension of final output
  device: 'cuda' #device to place training/testing data batches
  bnorm: True #enable or disable batch normalization. implemented only for cnn_lstm model
  
training_configuration:
  dataset_type: "real" #type of training/testing data. Options: real, scenegraph
  task_type: 'collision_prediction' #Task options. Options: sequence_classification, graph_classification, collision_prediction
  n_fold: 5 #number of folds for n-fold cross validation
  learning_rate: 0.00005 
  epochs: 200
  split_ratio: 0.3 #train-test split ratio
  downsample: False
  seed: 0 #seed used for train-test split
  batch_size: 32 #batch size of training, testing data
  test_step: 10 #perform test validation every n epochs
  weight_decay: 0.0005
  
wandb_configuration:
  entity: 'aicps'
  project: 'sg2vec'
