---
location_data:
    input_path: '/home/louisccc/NAS/louisccc/av/roadscene2vec_pkls/571_honda_image_dataset_5_frame_128x72.pkl'
    #TODO: revise this configuration file. copy it from 3_train_graph_learning.py argparser config
    #TODO: add a comment to every line of this config explaining what the config parameter represents/what options are available
    transfer_path: null #Path to the transfer file.
    
model_configuration:
  model: 'cnn_lstm' #options: mrgcn, mrgin, cnn, cnn_lstm, resnet50, resnet50_lstm, lstm, gru
  num_layers: 3
  load_model: False
  model_load_path: './model/model_best_val_loss_.vec.pt'
  model_save_path: './model/model_best_val_loss_.vec.pt'
  dropout: 0.1 #0.25
  nclass: 2
  device: 'cuda'
  bnorm: True #enable or disable batch normalization
  
training_configuration:
  dataset_type: "real" #real, scenegraph
  task_type: 'collision_prediction' #options: sequence_classification, graph_classification, collision_prediction
  n_fold: 5
  learning_rate: 0.00005 #0.00005
  epochs: 200
  split_ratio: 0.3
  downsample: False
  seed: 0 #random.randint(0,2**32)
  weight_decay: 0.0005
  batch_size: 32
  test_step: 10
  stats_path: 'best_stats.csv'
  
wandb_configuration:
  entity: 'aicps'
  project: 'roadscene2vec'
