---
dataset_type: 'carla'
#TODO: revise this configuration file
location_data:
    input_path: '/home/louisccc/NAS/louisccc/av/synthesis_data/271_carla'
    data_save_path: '/home/louisccc/NAS/louisccc/av/sg2vec_pkls/271_carla_scenegraph.pkl'
