---
location_data:
    input_path: '/home/harsimrat/av_data/entire_lanechange_seq_new_imp_sg.pkl'
    #TODO: revise this configuration file. copy it from 3_train_graph_learning.py argparser config
    #TODO: add a comment to every line of this config explaining what the config parameter represents/what options are available
    #scenegraph_dataset_object_path: 'C:/av_data/preprocessed_dataset.pkl'
    transfer_path: null #Path to the transfer file.
    
model_configuration:
  num_relations: 12 #num of types of relations extracted, needed only for graph based models 
  model: 'mrgcn' #options: mrgcn, mrgin, cnn, cnn_lstm, resnet50_lstm, lstm, gru
  num_layers: 2
  load_model: False
  num_of_classes: 8 #num of actors
  conv_type: 'FastRGCNConv'
  hidden_dim: 64
  layer_spec: null
  pooling_type: 'sagpool'
  pooling_ratio: 0.5
  readout_type: 'add'
  temporal_type: 'lstm_attn'
  lstm_input_dim: 50
  lstm_output_dim: 20
  nclass: 2
  dropout: 0.1 #0.25
  device: 'cuda'
  activation: 'relu'
  model_load_path: './model/model_best_val_loss_.vec.pt'
  model_save_path: './model/model_best_val_loss_.vec.pt'
  num_of_classes: 9 #8 #num of actors
  
training_configuration:
  dataset_type: "scenegraph" #real, scenegraph
  scenegraph_dataset_type: "real" #options: carla, real
  task_type: 'sequence_classification' #options: cnn_image_classification, sequence_classification, graph_classification, collision_prediction
  n_fold: 5
  learning_rate: 0.0001 #0.00005
  epochs: 200
  transfer_path: ''
  split_ratio: 0.3
  downsample: False
  seed: 0 #random.randint(0,2**32)
  weight_decay: 0.0005
  batch_size: 32
  test_step: 10
  stats_path: 'best_stats.csv'
  
wandb_configuration:
  entity: 'aicps'
  project: 'sg2vec'
