---
location_data:
    input_path: '/home/louisccc/NAS/louisccc/av/sg2vec_pkls/1043_carla_image_dataset_5_frame_128x72.pkl'
    #TODO: revise this configuration file. copy it from 3_train_graph_learning.py argparser config
    #TODO: add a comment to every line of this config explaining what the config parameter represents/what options are available

    transfer_path: null #Path to the transfer file.
model_configuration:
  model: 'cnn_lstm' #options: mrgcn, mrgin, cnn, cnn_lstm, resnet50, resnet50_lstm, lstm, gru
  num_layers: 3
  load_model: False
  num_relations: 12 #num of types of relations extracted, needed only for graph based models 
training_configuration:
  task_type: 'collision_prediction' #options: sequence_classification, graph_classification, collision_prediction
  scenegraph_dataset_type: carla #options: carla, real, null
  dataset_type: "real" #options: real, scenegraph
  n_fold: 5
  num_of_classes: 9 #8 #num of actors
  learning_rate: 0.00005 #0.00005
  epochs: 200
  cache_path: '../script/image_dataset.pkl'
  transfer_path: ''
  model_load_path: './model/model_best_val_loss_.vec.pt'
  model_save_path: './model/model_best_val_loss_.vec.pt'
  split_ratio: 0.3
  downsample: False
  seed: 0 #random.randint(0,2**32)
  activation: 'relu'
  weight_decay: 0.0005
  dropout: 0.1 #0.25
  nclass: 2
  batch_size: 32
  bnorm: True #enable or disable batch normalization
  device: 'cuda'
  test_step: 10
  conv_type: 'FastRGCNConv'
  num_layers: 3
  hidden_dim: 64
  layer_spec: null
  pooling_type: 'sagpool'
  pooling_ratio: 0.5
  readout_type: 'add'
  temporal_type: 'lstm_seq'
  lstm_input_dim: 50
  lstm_output_dim: 20
  stats_path: 'best_stats.csv'
wandb_configuration:
  entity: 'aicps'
  project: 'sg2vec'
