---
location_data:
    input_path: '/home/arnav/271_carla_image_dataset_20_frame.pkl'
    #TODO: revise this configuration file. copy it from 3_train_graph_learning.py argparser config
    #scenegraph_dataset_object_path: 'C:/av_data/preprocessed_dataset.pkl'
    transfer_path: null #Path to the transfer file.
model_configuration:
  model: 'cnn'
  num_layers: 3
  load_model: False
training_configuration:
  task_type: 'cnn image classification'
  scenegraph_dataset_type: "carla" #carla or real
  n_fold: 1 # 2
  num_of_classes: 8 #num of actors
  learning_rate: 0.0001 #0.00005 
  epochs: 200
  cache_path: '../script/image_dataset.pkl'
  transfer_path: ''
  model_load_path: './model/model_best_val_loss_.vec.pt'
  model_save_path: './model/model_best_val_loss_.vec.pt'
  split_ratio: 0.3
  downsample: False
  seed: 2063609112 #random.randint(0,2**32)
  activation: 'relu'
  weight_decay: 0.0005
  dropout: 0.1 #0.25
  nclass: 2
  batch_size: 32
  device: 'cpu'
  test_step: 10
  conv_type: 'FastRGCNConv'
  num_layers: 3
  hidden_dim: 64
  layer_spec: null
  pooling_type: 'sagpool'
  pooling_ratio: 0.5
  readout_type: 'mean'
  temporal_type: 'lstm_attn'
  lstm_input_dim: 50
  lstm_output_dim: 20
  stats_path: 'best_stats.csv'
wandb_configuration:
  entity: 'aicps'
  project: 'sg2vec'